// <auto-generated />
using KubicekKocnar.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KubicekKocnar.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241129173245_west1")]
    partial class west1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("KubicekKocnar.Server.Models.Block", b =>
                {
                    b.Property<uint>("BlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint?>("Texture0")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Texture1")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Texture2")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Texture3")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Texture4")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Texture5")
                        .HasColumnType("INTEGER");

                    b.HasKey("BlockId");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("KubicekKocnar.Server.Models.Feature", b =>
                {
                    b.Property<uint>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Params")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.Property<double>("Z")
                        .HasColumnType("REAL");

                    b.HasKey("FeatureId");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("KubicekKocnar.Server.Models.Level", b =>
                {
                    b.Property<uint>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint?>("NextLevelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LevelId");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("KubicekKocnar.Server.Models.Light", b =>
                {
                    b.Property<int>("LightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Color")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Intensity")
                        .HasColumnType("REAL");

                    b.Property<uint?>("LevelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Z")
                        .HasColumnType("INTEGER");

                    b.HasKey("LightId");

                    b.HasIndex("LevelId");

                    b.ToTable("Lights");
                });

            modelBuilder.Entity("KubicekKocnar.Server.Models.PlacedBlock", b =>
                {
                    b.Property<uint>("PlacedBlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Block")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("LevelId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.Property<double>("Z")
                        .HasColumnType("REAL");

                    b.HasKey("PlacedBlockId");

                    b.HasIndex("LevelId");

                    b.ToTable("PlacedBlocks");
                });

            modelBuilder.Entity("KubicekKocnar.Server.Models.Texture", b =>
                {
                    b.Property<uint>("TextureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("src")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("TextureId");

                    b.ToTable("Textures");
                });

            modelBuilder.Entity("KubicekKocnar.Server.Models.Light", b =>
                {
                    b.HasOne("KubicekKocnar.Server.Models.Level", null)
                        .WithMany("Lights")
                        .HasForeignKey("LevelId");
                });

            modelBuilder.Entity("KubicekKocnar.Server.Models.PlacedBlock", b =>
                {
                    b.HasOne("KubicekKocnar.Server.Models.Level", null)
                        .WithMany("Blocks")
                        .HasForeignKey("LevelId");
                });

            modelBuilder.Entity("KubicekKocnar.Server.Models.Level", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("Lights");
                });
#pragma warning restore 612, 618
        }
    }
}
