// <auto-generated />
using System;
using KubicekKocnar.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KubicekKocnar.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241130200545_sfsd")]
    partial class sfsd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("KubicekKocnar.Server.Models.Block", b =>
                {
                    b.Property<uint>("BlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint?>("Texture0")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Texture1")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Texture2")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Texture3")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Texture4")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Texture5")
                        .HasColumnType("INTEGER");

                    b.HasKey("BlockId");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("KubicekKocnar.Server.Models.Feature", b =>
                {
                    b.Property<uint>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("LevelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Params")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.Property<double>("Z")
                        .HasColumnType("REAL");

                    b.HasKey("FeatureId");

                    b.HasIndex("LevelId");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("KubicekKocnar.Server.Models.Game", b =>
                {
                    b.Property<uint>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Published")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("KubicekKocnar.Server.Models.Level", b =>
                {
                    b.Property<uint>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint?>("NextLevelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LevelId");

                    b.HasIndex("GameId");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("KubicekKocnar.Server.Models.Light", b =>
                {
                    b.Property<uint>("LightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Color")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Intensity")
                        .HasColumnType("REAL");

                    b.Property<uint>("LevelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Z")
                        .HasColumnType("INTEGER");

                    b.HasKey("LightId");

                    b.HasIndex("LevelId");

                    b.ToTable("Lights");
                });

            modelBuilder.Entity("KubicekKocnar.Server.Models.PlacedBlock", b =>
                {
                    b.Property<uint>("PlacedBlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Block")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("LevelId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.Property<double>("Z")
                        .HasColumnType("REAL");

                    b.HasKey("PlacedBlockId");

                    b.HasIndex("LevelId");

                    b.ToTable("PlacedBlocks");
                });

            modelBuilder.Entity("KubicekKocnar.Server.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("KubicekKocnar.Server.Models.Texture", b =>
                {
                    b.Property<uint>("TextureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("src")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("TextureId");

                    b.ToTable("Textures");
                });

            modelBuilder.Entity("KubicekKocnar.Server.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<string>("RolesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsersId")
                        .HasColumnType("TEXT");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("KubicekKocnar.Server.Models.Feature", b =>
                {
                    b.HasOne("KubicekKocnar.Server.Models.Level", null)
                        .WithMany("Features")
                        .HasForeignKey("LevelId");
                });

            modelBuilder.Entity("KubicekKocnar.Server.Models.Game", b =>
                {
                    b.HasOne("KubicekKocnar.Server.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("KubicekKocnar.Server.Models.Level", b =>
                {
                    b.HasOne("KubicekKocnar.Server.Models.Game", "Game")
                        .WithMany("Levels")
                        .HasForeignKey("GameId");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("KubicekKocnar.Server.Models.Light", b =>
                {
                    b.HasOne("KubicekKocnar.Server.Models.Level", null)
                        .WithMany("Lights")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KubicekKocnar.Server.Models.PlacedBlock", b =>
                {
                    b.HasOne("KubicekKocnar.Server.Models.Level", null)
                        .WithMany("Blocks")
                        .HasForeignKey("LevelId");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("KubicekKocnar.Server.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KubicekKocnar.Server.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KubicekKocnar.Server.Models.Game", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("KubicekKocnar.Server.Models.Level", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("Features");

                    b.Navigation("Lights");
                });
#pragma warning restore 612, 618
        }
    }
}
